spring.application.name=social-service
server.port=8086

spring.config.import=optional:configserver:http://config-server:8888

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/dayquest_social
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=social_schema
spring.flyway.enabled=true
spring.flyway.schemas=social_schema
spring.flyway.default-schema=social_schema
spring.flyway.create-schemas=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.dayquest.socialservice=INFO

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

