services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - dayquest-network
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - dayquest-network

  api-gateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    container_name: api-gateway
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - dayquest-network

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - dayquest-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - dayquest-network

volumes:
  postgres:

networks:
  dayquest-network:
    name: dayquest-network
    driver: bridge
