FROM maven:3.9.4-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:resolve

FROM maven:3.9.4-eclipse-temurin-17-alpine
WORKDIR /app
COPY --from=builder /root/.m2 /root/.m2
CMD ["mvn", "spring-boot:run"]
