services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - dayquest-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    depends_on:
      - config-server
      - eureka-server
    networks:
      - dayquest-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVER_PORT}:${NOTIFICATION_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    depends_on:
      - config-server
      - eureka-server
    networks:
      - dayquest-network

  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    env_file:
      - stack.env
    depends_on:
      - config-server
      - eureka-server
    restart: unless-stopped
    networks:
      - dayquest-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - stack.env
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - dayquest-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - dayquest-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dayquest-network
    restart: unless-stopped


volumes:
  postgres:
  pgadmin-data:
  rabbitmq_data:

networks:
  dayquest-network:
    name: dayquest-network
    driver: bridge
